# Generic
# -------------------------
ensemblename: ensemble_raml_genconf15
save_checkpoint_every : 4000
caption_model: show_tell
batch_size : 5
beam_size : 3
seq_per_img : 15
input_json : data/coco/genConf_cocotalk.json
input_h5 : data/coco/genConf_cocotalk.h5
restart : 1
start_from_best : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
model: [fn_raml_exp_tau005_isolated_a03_genconf15_v2, fn_raml_exp_tau005_isolated_a03_genconf15_v3, fn_raml_exp_tau005_isolated_a03_genconf15_v4, fn_raml_exp_tau005_isolated_a03_genconf15_v5 ]

