# Generic
# -------------------------
modelname : fn_baseline_resnet50_genconf15
start_from : save/extended/baseline_resnet50_genconf15
start_from_best: 1
cnn_model : resnet50
caption_model : show_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size : 10
beam_size : 3
input_json : data/coco/genConf_cocotalk.json
input_h5 : data/coco/genConf_cocotalk.h5
seq_per_img : 15
restart : 1
val_images_use : -1
finetune_cnn_after : 0
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
