# Generic
# -------------------------
modelname : fn_raml_hamming_tau10_a03_lr1
start_from: save/raml_hamming_tau10_a03
start_from_best: 1
cnn_model : resnet50
cnn_learning_rate: 1.0
caption_model : show_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size : 10
beam_size : 3
#--------------------------RAML
raml_loss : 1
raml_version : hamming
raml_tau : 1.0
raml_alpha : 0.3
#--------------------------//RAML
input_json : data/coco/cocotalk.json
input_h5 : data/coco/cocotalk.h5
restart : 1
val_images_use : -1
finetune_cnn_after : 0
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4 
