# Generic
# -------------------------
modelname : raml_fn_exp_tau005_isolated_a03
start_from :  save/raml_exp_tau005_isolated_a03
start_from_best : 1
grad_clip : 0.5
cnn_learning_rate : 1.0
cnn_model : resnet50
caption_model : show_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size : 10
beam_size : 3
#--------------------------RAML
raml_loss : 1
raml_version : exp
raml_tau : 0.05
raml_isolate : 1
raml_alpha: 0.3
#--------------------------//RAML
input_json : data/coco/cocotalk.json
input_h5 : data/coco/cocotalk.h5
restart : 1
val_images_use : -1

finetune_cnn_after : 0
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4

# scheduled_sampling_start : 15
# scheduled_sampling_increase_every: 3
# scheduled_sampling_increase_prob: 0.03
# scheduled_sampling_max_prob: 0.15
