# Generic
# -------------------------
modelname : raml_hamming_sampling_tau09_td0092_glove
cnn_model : resnet50
caption_model : show_tell_raml
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size : 10
beam_size : 3
input_json : data/coco/cocotalk.json
input_h5 : data/coco/cocotalk.h5
seq_per_img : 5
restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

#--------------------------RAML
raml_loss : 0
raml_version: vocab_glove
similarity_matrix : data/Glove/cocotalk_similarities_v2.pkl
raml_tau_sample : 0.092
raml_tau : 0.9
less_confident : 1
raml_alpha: 0.3
#--------------------------//RAML

