# Generic
# -------------------------
modelname : resnet50_mil_1000words_stops_500px
cnn_model : vgg16
cnn_fc_feat : fc8
caption_model : show_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size :1
input_json : data/coco/cocotalk1000_stops.json
input_h5 : data/coco/cocotalk1000_stops.h5
seq_per_img : 5
upsampling_size : 500
restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 1e-5
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

#--------------------------RAML
raml_loss : 0
#--------------------------//RAML

