# Generic
# -------------------------
modelname : textLM/textLM_multivae
save_checkpoint_every : 1500
batch_size : 40
input_json : data/coco/cocotalk.json
input_h5 : data/coco/cocotalk.h5
restart : 1
val_images_use : 1000
learning_rate : 1e-4
lm_model : rnn_multi_vae
seq_per_img : 5
rnn_size : 512
z_size: 20
z_interm_size : 200
kld_weight: 1.0
