modelname : adaatt_resnet152_repord
caption_model : adaptive_attention

restart : 1
val_images_use : -1
save_checkpoint_every : 4000

optim_alpha : 0.8

cnn_model : resnet152

fc_feat_size : 2048
att_feat_size : 2048
region_size : 7
use_adaptive_pooling : 0
rnn_size : 512
drop_feat_im : 0

batch_size : 10
input_data : data/coco/cocotalk_seq18

grad_clip : .1
learning_rate : 5e-4
learning_rate_decay_start : -1
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

finetune_cnn_after : 20
cnn_learning_rate : .02
finetune_cnn_slice : 6
max_epochs : 50
beam_size : 3
