# Generic
# -------------------------
modelname : attend_resnet50_nonorm_lr
cnn_model : resnet50
caption_model : show_attend_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
att_feat_size : 2048
num_regions : 512
rnn_size : 512
batch_size : 10
normalize_batch : 0

input_data : data/coco/cocotalk

restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 0.001
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
