# Generic
# -------------------------
modelname : baseline_resnet50_genLMv2_ltd
cnn_model : resnet50
caption_model : show_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size : 10
beam_size : 3
input_json : data/coco/genLMv2_ltd_cocotalk.json
input_h5 : data/coco/genLMv2_ltd_cocotalk.h5
seq_per_img : 10
restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
