modelname : baseline_showtell152
caption_model : show_tell

restart : 1
val_images_use : -1
save_checkpoint_every : 4000

optim_alpha : 0.8

finetune_cnn_after : -1
cnn_model : resnet152

fc_feat_size : 2048
rnn_size : 512

batch_size : 10
input_data : data/coco/cocotalk

beam_size : 3

