modelname : baseline_GloveW_coco_free_showtell152
caption_model : show_tell
cnn_model : resnet152
init_decoder_W:  data/Glove/glove_coco_d512_w15_matrix.pkl
freeze_decoder_W : 0 
input_data : data/coco/cocotalk

# Loss:
loss_version : ml


