modelname : baseline_GloveW_frozen_showtell152
caption_model : show_tell
cnn_model : resnet152
init_decoder_W:  data/Glove/cocotalk_glove_v2.pkl
freeze_decoder_W : 1
input_data : data/coco/cocotalk

# Loss:
loss_version : ml

