modelname : baseline_proj_embed_tied_Glove_coco_free_showtell152
caption_model : show_tell
cnn_model : resnet152
init_decoder_W:  data/Glove/glove_coco_d512_w15_matrix.pkl
freeze_decoder_W : 0
init_decoder_Proj:  data/Glove/glove_coco_d512_w15_matrix.pkl
freeze_decoder_Proj : 0
tie_decoder_W_Proj : 1
input_data : data/coco/cocotalk

# Loss:
loss_version : ml


