modelname : baseline_resnet50_msc_bs20
caption_model : show_tell

restart : 1
val_images_use : -1
save_checkpoint_every : 4000

optim_alpha : 0.8

finetune_cnn_after : -1
cnn_model : resnet50

fc_feat_size : 2048
rnn_size : 512

batch_size : 20
input_data : data/coco/cocotalk

grad_clip : .1
learning_rate : 4e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

beam_size : 3

