# Generic
# -------------------------
modelname : bs_conf_gtlm_genlm_cider_tsent10_b01
restart : 1

caption_model : show_tell
cnn_model : resnet50

batch_size : 10
input_data : data/coco/bootstrap_confusion_s15
seq_per_img : 15
val_images_use : -1
save_checkpoint_every : 4000

finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

# Loss:
bootstrap : 1
gt_loss_version : ml
augmented_loss_version : ml
bootstrap_score: cider
tau_sent: 1
beta: 0.1
