# Generic
# -------------------------
modelname : cider2_tsent11_a03
restart : 1

caption_model : show_tell
cnn_model : resnet50

batch_size : 10
input_data : data/coco/cocotalk
val_images_use : -1
save_checkpoint_every : 4000

finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

# Loss:
sample_cap: 1
loss_version : cider
sentence_loss_version : 2
tau_sent : 1.1
alpha_sent : 0.3
