modelname : debug
caption_model : show_tell

restart : 1
val_images_use : 10
save_checkpoint_every : 40
cnn_model : resnet50
batch_size : 5
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
tau_sent : .3
alpha_sent : 0.4
reward : cider
stratify_reward : 0
importance_sampler : hamming

