# Generic
# -------------------------
ensemblename: ensemble_baselines_lr
save_checkpoint_every : 4000
caption_model: show_tell
batch_size : 10
beam_size : 3
seq_per_img : 5
input_json : data/coco/cocotalk.json
input_h5 : data/coco/cocotalk.h5
restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 5e-6
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
model: [baseline_fn_resnet50, fn_baseline_resnet50_genconf15_lr1, fn_raml_exp_tau005_isolated_a03_genconf15_lr1]

