ensemblename : debug
models: [fncnn6_reset_combine_importance_qhamming_limited2_tsent03_rcider_tsent05_a04_word_coco_tword009_idf10_a03_topdown_WE_fulltrain_1, fncnn6_reset_combine_importance_qhamming_limited2_tsent03_rcider_tsent05_a04_word_coco_tword009_idf10_a03_topdown_WE_fulltrain_2]
verbose : 1
image_folder: data/coco/images/val2014
image_list: data/coco/images/val.txt
beam_size: 3

