# Generic
# -------------------------
modelname : fncnn_sample2_hamming_tsent017_a04
start_from : save/sample2_hamming_tsent017_a04
restart : 1
start_from_best : 1

caption_model : show_tell
cnn_model : resnet50
cnn_learning_rate : 1.0

batch_size : 10
input_data : data/coco/cocotalk
val_images_use : -1
save_checkpoint_every : 4000

finetune_cnn_after : 0
finetune_cnn_slice : 3
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 25


# Loss:
sample_reward: 1
sentence_loss_version : 2
loss_version : hamming
tau_sent : .17
alpha_sent : 0.4
