modelname : fncnn6_word2_coco_tword013_a03_topdown_resnet152_msc
start_from : save/word2_coco_tword013_a03_topdown_resnet152_msc
start_from_best : 1
caption_model : top_down


cnn_learning_rate : 1.
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk
similarity_matrix : data/Glove/train_coco_similarities.pkl

finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

# Loss:
loss_version : word
tau_word : 0.13
rare_tfidf : 0
alpha_word : 0.3

