modelname : fncnn6_reset_word_coco_tword013_a05_topdown
start_from : save/word_coco_tword013_a05_topdown152
start_from_best : 1
caption_model : top_down


cnn_learning_rate : 1.
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk
similarity_matrix : data/Glove/train_coco_similarities.pkl

reset_optimizer : 1
finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

# Loss:
loss_version : word
tau_word : 0.13
rare_tfidf : 0
alpha_word : 0.5
