modelname : fncnn6_reset_strat_lazy_rhamming_pool2_tsent03_a04_topdown
start_from : save/strat_lazy_rhamming_pool2_tsent03_a04_topdown
start_from_best : 1

caption_model : top_down
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub : 2
lazy_rnn : 1
stratify_reward  : 1
tau_sent : .3
alpha_sent : 0.4

reset_optimizer : 1
finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

