modelname : fncnn6_reset_word_coco_tword009_idf10_a03_topdown_seed2
start_from : save/word_coco_tword009_idf10_a03_topdown_seed2
start_from_best : 1
seed : 2

caption_model : top_down
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

reset_optimizer : 1
finetune_cnn_after : 0
finetune_cnn_slice : 6

learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

# Loss:
loss_version : word
similarity_matrix : data/Glove/train_coco_similarities.pkl
promote_rarity : 1
tau_word : 0.09
alpha_word : 0.3


