modelname : fncnn6_reset_strat_rhamming_pool0_tsent01_a04_showtell152
start_from : save/strat_rhamming_pool0_tsent01_a04_showtell152
start_from_best : 1

caption_model : show_tell 
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub : 0
lazy_rnn : 0
stratify_reward  : 1
tau_sent : .1
alpha_sent : 0.4

reset_optimizer : 1
finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

