modelname : fncnn6_reset_word_coco_tword015_a07_showtell152_seed4
start_from : save/word_coco_tword015_a07_showtell152_seed4
start_from_best : 1
seed : 4

caption_model : show_tell 
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

reset_optimizer : 1
finetune_cnn_after : 0
finetune_cnn_slice : 6

learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30


# Loss:
loss_version : word
similarity_matrix : data/Glove/train_coco_similarities.pkl
promote_rarity: 0
tau_word : 0.15
alpha_word : 0.7

