modelname : fncnn6_reset_importance_qhamming_pool1_tsent017_rbleu4_tsent05_a04_showtell152
start_from : save/importance_qhamming_pool1_tsent017_rbleu4_tsent05_a04_showtell152
start_from_best : 1


caption_model : show_tell
cnn_model : resnet152
input_data : data/coco/cocotalk
# loss:
loss_version : seq
alpha_sent : 0.4

stratify_reward : 0
reward : bleu4
tau_sent : 0.5
refs_mode : 1

importance_sampler : hamming
tau_sent_q : 0.17
limited_vocab_sub : 1

reset_optimizer : 1
finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

