modelname : fncnn6_sample2_hamming_tsent03_limited2_a04_topdown_resnet152
start_from : save/sample2_hamming_tsent03_limited2_a04_topdown_resnet152_msc
start_from_best : 1
caption_model : top_down

cnn_model : resnet152
batch_size : 10
input_data : data/coco/cocotalk

finetune_cnn_after : 0
finetune_cnn_slice : 6

learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

# Loss:
loss_version : seq
reward : hamming
stratify_reward : 1
tau_sent : .3
limited_vocab_sub : 2
alpha_sent : 0.4
