# Generic
# -------------------------
modelname : fncnn_complete_combine_word2_tword015_coco_idf_a07_hamming_tsent017_a04
start_from : save/complete_combine_word2_tword015_coco_idf_a07_hamming_tsent017_a04
start_from_best : 1
restart : 1

caption_model : show_tell
cnn_model : resnet50
cnn_learning_rate: 1.0

batch_size : 10
input_data : data/coco/cocotalk
val_images_use : -1
save_checkpoint_every : 4000

finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 25

# Loss:
combine_loss : 1
sample_reward: 1
loss_version : hamming
tau_sent : .17
alpha_sent : 0.4
tau_word: 0.15
rare_tfidf : 1
similarity_matrix : data/Glove/train_coco_similarities.pkl
alpha_word : 0.7

