modelname : fncnn6_sample2_hamming_tsent03_limited2_a05_showtell
start_from : save/sample2_hamming_limited2_tsent03_a05
start_from_best : 1
caption_model : show_tell

cnn_model : resnet50
batch_size : 10
input_data : data/coco/cocotalk

finetune_cnn_after : 0
finetune_cnn_slice : 6

learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4
max_epochs : 30

# Loss:
loss_version : seq
reward : hamming
stratify_reward : 1
tau_sent : .3
limited_vocab_sub : 2
alpha_sent : 0.5
