modelname : fncnn6_adaatt_resnet152_msc_maxout
start_from : save/adaatt_resnet152_msc_maxout
start_from_best : 1
caption_model : adaptive_attention

restart : 1
val_images_use : -1
save_checkpoint_every : 4000

optim_alpha : 0.8

cnn_model : resnet152
cnn_learning_rate : 1.0

fc_feat_size : 2048
att_feat_size : 2048
region_size : 7
use_adaptive_pooling : 0
use_maxout : 1
rnn_size : 512
drop_feat_im : 0

batch_size : 10
input_data : data/coco/cocotalk

grad_clip : .1
beam_size : 3

finetune_cnn_after : 0
finetune_cnn_slice : 6
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4


max_epochs : 30
