# Generic
# -------------------------
modelname : fncnn_word2_tword015_coco_idf_a09_skip5
start_from : save/word2_tword015_CocoGlove_idf_bis_a09
start_from_best : 1
restart : 1

caption_model : show_tell
cnn_model : resnet50
cnn_learning_rate: 1.0

batch_size : 10
input_data : data/coco/cocotalk
similarity_matrix : data/Glove/train_coco_similarities.pkl
val_images_use : -1
save_checkpoint_every : 4000

finetune_cnn_after : 0
finetune_cnn_slice : 5
learning_rate : 1e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.8
learning_rate_decay_every: 4

# Loss:
sample_cap: 1
loss_version : word2
tau_word : 0.15
rare_tfidf : 1
word_add_entropy : 0
alpha : 0.9
