modelname : importance_qhamming_limited2_tsent03_rcider_tsent05_a04_topdown_seed3
caption_model : top_down
cnn_model : resnet152
seed : 3
input_data : data/coco/cocotalk
# loss:
loss_version : seq
stratify_reward : 0
reward : cider
importance_sampler : hamming
alpha_sent : 0.4
tau_sent : 0.5
tau_sent_q : 0.3
limited_vocab_sub : 2

