modelname : importance_lazy_qp_rcider_tsent05_a04_topdown
caption_model : top_down
cnn_model : resnet152
input_data : data/coco/cocotalk
# loss:
loss_version : seq
stratify_reward : 0
reward : cider
importance_sampler : greedy
alpha_sent : 0.4
tau_sent : 0.5
lazy_rnn : 1

