modelname : importance_qhamming_pool2_tsent03_rbleu4_mode2_clip07_tsent05_a05_showtell152

caption_model : show_tell
cnn_model : resnet152
input_data : data/coco/cocotalk
# loss:
loss_version : seq
alpha_sent : 0.5

stratify_reward : 0
reward : bleu4
tau_sent : 0.5
clip_reward : 0.7
refs_mode : 2

importance_sampler : hamming
tau_sent_q : 0.3
limited_vocab_sub : 2

