modelname : importance_qhamming_pool2_tsent03_rcst_a05_showtell152

caption_model : show_tell
cnn_model : resnet152
input_data : data/coco/cocotalk
# loss:
loss_version : seq
stratify_reward : 0
reward : constant
importance_sampler : hamming
alpha_sent : 0.5
tau_sent : 0
tau_sent_q : 0.3
limited_vocab_sub : 2

