modelname : importance_qhamming_pool2_tsent03_rbleu2_tsent08_a05_showtell152

caption_model : show_tell
cnn_model : resnet152
input_data : data/coco/cocotalk
# loss:
loss_version : seq
alpha_sent : 0.5

stratify_reward : 0
reward : bleu2
tau_sent : 0.8

importance_sampler : hamming
tau_sent_q : 0.3
limited_vocab_sub : 2

