modelname : importance_qhamming_pool2_tsent03_rbleu4_mode0_tsent07_a04_topdown

caption_model : top_down
cnn_model : resnet152
input_data : data/coco/cocotalk
# loss:
loss_version : seq
alpha_sent : 0.5

stratify_reward : 0
reward : bleu4
tau_sent : 0.7
refs_mode : 0

importance_sampler : hamming
tau_sent_q : 0.3
limited_vocab_sub : 2

