# Generic
# -------------------------
modelname : raml_clip_norm_m95
cnn_model : resnet50
caption_model : show_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
batch_size : 10
beam_size : 3
#--------------------------RAML
raml_loss : 1
raml_version : clip
raml_isolate : 0
raml_normalize : 1
raml_margin : 0.95
#--------------------------//RAML
input_json : data/coco/cocotalk.json
input_h5 : data/coco/cocotalk.h5
restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
smoothing_version : 2
