modelname : sample2_hamming_tsent03_limited2_a04_topdown_resnet152_msc_v3
caption_model : top_down
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
stratify_reward : 1
reward : hamming
tau_sent : .3
limited_vocab_sub : 2
alpha_sent : 0.4

