modelname : sample2_hamming_tsent017_a04_topdown_resnet152_genconf15
caption_model : top_down
cnn_model : resnet152

input_data : data/coco/genConf_cocotalk
batch_size : 10
seq_per_img : 15

# Loss:
loss_version : seq
reward : hamming
stratify_reward : 1
tau_sent : .17
alpha_sent : 0.4

