modelname : sample2_hamming_tsent017_limited1_a04_topdown_resnet152_msc_seed12
caption_model : top_down
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
stratify_reward : 1
reward : hamming
tau_sent : .17
limited_vocab_sub : 1
alpha_sent : 0.4
seed : 12

