modelname : strat_lazy_rhamming_pool1_tsent017_a04_showtell152
caption_model : show_tell 
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub : 1
lazy_rnn : 1
stratify_reward  : 1
tau_sent : .17
alpha_sent : 0.4

