modelname : strat_rhamming_pool0_tsent01_a04_topdown_seed3
caption_model : top_down
cnn_model : resnet152
seed : 3
batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub : 0
lazy_rnn : 0
stratify_reward  : 1
tau_sent : .1
alpha_sent : 0.4

