modelname : strat_lazy_rhamming_pool0_tsent01_a04_topdown
caption_model : top_down
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub : 0
lazy_rnn : 1
stratify_reward  : 1
tau_sent : .1
alpha_sent : 0.4

