modelname : strat_rhamming_pool0_tsent01_a04_showtell152_seed4
caption_model : show_tell 
cnn_model : resnet152
seed : 4

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : seq
reward : hamming
limited_vocab_sub : 0
lazy_rnn : 0
stratify_reward  : 1
tau_sent : .1
alpha_sent : 0.4

