modelname : word2_tword015_coco_a07_penalize01_showtell_resnet50
restart : 1

caption_model : show_tell
cnn_model : resnet50

batch_size : 10
input_data : data/coco/cocotalk
similarity_matrix : data/Glove/train_coco_similarities.pkl
val_images_use : -1
save_checkpoint_every : 4000

finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3

# Loss:
sample_cap: 1
loss_version : word2
tau_word : 0.15
word_add_entropy : 0
alpha_word : 0.7
penalize_confidence: 0.1
