# Generic
# -------------------------
modelname : word2_tword02_a09_attend
cnn_model : resnet50
caption_model : show_attend_tell
save_checkpoint_every : 4000
fc_feat_size : 2048
att_feat_size : 2048
num_regions : 512
rnn_size : 512
batch_size : 10
input_data : data/coco/cocotalk

restart : 1
val_images_use : -1
finetune_cnn_after : -1
learning_rate : 5e-4
learning_rate_decay_start : 5
learning_rate_decay_rate : 0.6
learning_rate_decay_every: 3
#
# Loss:
sample_cap: 1
loss_version : word2
tau_word : 0.2
word_add_entropy : 0
alpha_word : 0.9
