modelname : word_coco_tword009_idf10_a03_topdown
caption_model : top_down
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

# Loss:
loss_version : word
similarity_matrix : data/Glove/train_coco_similarities.pkl
rare_tfidf: 1
tau_word : 0.09
alpha_word : 0.3


