modelname : word_coco_tword009_idf10_a07_proj_embed_tied_init_free_showtell152
caption_model : show_tell
cnn_model : resnet152
init_decoder_W:  data/Glove/glove_coco_d512_w15_matrix.pkl
freeze_decoder_W : 0
init_decoder_Proj:  data/Glove/glove_coco_d512_w15_matrix.pkl
freeze_decoder_Proj : 0
tie_decoder_W_Proj : 1
input_data : data/coco/cocotalk

# Loss:
loss_version : word
similarity_matrix : data/Glove/train_coco_similarities.pkl
rare_tfidf: 1
tau_word : 0.09
alpha_word : 0.7




