modelname : word_coco_tword015_nodrop_a07_showtell152
caption_model : show_tell 
cnn_model : resnet152

batch_size : 10
input_data : data/coco/cocotalk

drop_x_lm : 0
# Loss:
loss_version : word
similarity_matrix : data/Glove/train_coco_similarities.pkl
rare_tfidf: 0
tau_word : 0.15
alpha_word : 0.7

